# Generated by Django 5.2.2 on 2025-06-05 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FitnessClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField()),
                ("instructor", models.CharField(max_length=100)),
                ("total_slots", models.PositiveIntegerField()),
                ("available_slots", models.PositiveIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["datetime"], name="fitness_fit_datetim_db436a_idx"
                    ),
                    models.Index(
                        fields=["instructor"], name="fitness_fit_instruc_ee1c8e_idx"
                    ),
                    models.Index(fields=["name"], name="fitness_fit_name_29445c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_email", models.EmailField(max_length=254)),
                (
                    "fitness_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fitness.fitnessclass",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["client_email"], name="fitness_boo_client__355648_idx"
                    ),
                    models.Index(
                        fields=["fitness_class", "client_email"],
                        name="fitness_boo_fitness_2f7df3_idx",
                    ),
                ],
                "unique_together": {("fitness_class", "client_email")},
            },
        ),
    ]
